### ISSUE TITLE
GET existing zonefile

### ISSUE THREAD

**Issue by ajlanghorn** [dyninc/dyn-rb#24]
Is there a way to issue an HTTP GET against an existing zone file using this Gem? The only workaround I can see so far is to download the rendered zonefiles from the UI, and then store them locally, but it would be much nicer if this Gem allowed for that. I suppose that this might be limited by API functionality.

**Comment by lhagemann** [comment]
@ajlanghorn take a look at the example here: 
https://github.com/dyninc/dyn-rb/blob/master/examples/dyn_traffic_examples.rb#L8

the `get_all` method will return all records in the zone.

**Comment by ajlanghorn** [comment]
@lhagemann Thanks; I didn't spot that. I'll give it a go!
